# Generated by Django 6.1.1 on 2026-09-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_one', to='dogs.dog')),
                ('dog_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_two', to='dogs.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_given', to='dogs.dog')),
                ('to_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='dogs.dog')),
            ],
            options={
                'unique_together': {('from_dog', 'to_dog')},
            },
        ),
    ]
